<main id="main" class="auth-layout"><div class="auth-intro"><span class="eyebrow">A clearer financial picture</span><h1>Make room<br>for what matters.</h1><p>Your income, expenses and documents.<br>One calm, organized workspace.</p><img src="<?= e(asset('auth-art.jpg')) ?>" alt="Money workspace with financial reports" width="620" height="360"></div><section class="auth-panel"><span class="eyebrow">MONEY ACCOUNT</span><h2><?= e($title) ?></h2><p class="muted"><?= $mode==='register'?'Start with a clean workspace for your business.':($mode==='login'?'Sign in to pick up where you left off.':($mode==='invite'?'You have been invited to '.e($invitation['workspace_name']).'.':'Keep your account secure.')) ?></p>
<?php require ROOT.'/app/views/partials/flash.php'; if($error): ?><div class="notice error" role="alert"><?= e($error) ?></div><?php endif ?>
<form method="post" class="stack-form" action="<?= e(url($mode,$token?['token'=>$token]:[])) ?>">
<?= csrf_field() ?>
<?php if($token): ?><input type="hidden" name="token" value="<?= e($token) ?>"><?php endif ?>
<?php if($mode==='register'||($mode==='invite'&&!current_user())): ?><label>Full name<input name="name" autocomplete="name" maxlength="190" value="<?= e(input('name')) ?>" required></label><?php endif ?>
<?php if(in_array($mode,['login','register','forgot-password'],true)): ?><label>Email address<input type="email" name="email" autocomplete="email" maxlength="190" value="<?= e(input('email')) ?>" required></label><?php endif ?>
<?php if($mode==='invite'): ?><div class="invitation-email"><?= e($invitation['email']) ?> <?= badge($invitation['role']) ?></div><?php endif ?>
<?php if($mode==='register'): ?><div class="form-grid"><label>Company name<input name="company" maxlength="190" value="<?= e(input('company')) ?>" autocomplete="organization" required></label><label>Currency<select name="currency"><?php foreach(['EUR','USD','GBP'] as $c): ?><option<?= selected(input('currency','EUR'),$c) ?>><?= $c ?></option><?php endforeach ?></select></label></div><?php endif ?>
<?php if(in_array($mode,['login','register','reset-password'],true)||($mode==='invite'&&!current_user())): ?><label>Password<div class="password-field"><input type="password" name="password" autocomplete="<?= $mode==='login'?'current-password':'new-password' ?>" <?= $mode!=='login'?'minlength="12"':'' ?> maxlength="72" required><button type="button" class="icon-button" data-toggle-password aria-label="Show password" title="Show password"><?= icon('lock') ?></button></div><?php if($mode!=='login'): ?><small>Use 12 or more characters.</small><?php endif ?></label><?php endif ?>
<?php if(in_array($mode,['register','reset-password'],true)||($mode==='invite'&&!current_user())): ?><label>Confirm password<input type="password" name="password_confirmation" autocomplete="new-password" minlength="12" maxlength="72" required></label><?php endif ?>
<?php if($mode==='login'): ?><a class="auth-forgot" href="<?= e(url('forgot-password')) ?>">Forgot password?</a><?php endif ?>
<button class="button primary full" type="submit"><?= e(match($mode){'login'=>'Sign in','register'=>'Create account','forgot-password'=>'Send reset link','reset-password'=>'Update password','invite'=>'Accept invitation'}) ?><?= icon('arrow-right') ?></button>
<?php if($mode==='register'): ?><p class="fine-print">By creating an account, you acknowledge the <a href="<?= e(url('privacy')) ?>">privacy notice</a>.</p><?php endif ?>
</form>
<p class="auth-switch"><?php if($mode==='login'): ?>New to Money? <a href="<?= e(url('register')) ?>">Create an account</a><?php else: ?>Already have an account? <a href="<?= e(url('login')) ?>">Sign in</a><?php endif ?></p>
<?php if($mode==='forgot-password'&&config('environment')==='local'): ?><p class="fine-print">Local development: account emails are saved in the private mail outbox. Email delivery is not connected.</p><?php endif ?>
</section></main>
