<div class="page-heading"><div><a class="back-link" href="<?= e(url('invoices')) ?>"><?= icon('arrow-left') ?>Invoices</a><h1><?= e($title) ?></h1></div><?php if($invoice): ?><div class="heading-actions"><?= badge($invoice['status']) ?><a class="button" href="<?= e(url('invoice-print',['id'=>$invoice['id']])) ?>"><?= icon('download') ?>Print / PDF</a></div><?php endif ?></div>
<?php if($error): ?><div class="notice error" role="alert"><?= e($error) ?></div><?php endif ?>
<?php if(!$invoice): ?>
<?php if(!$contacts): ?><div class="notice warning">Add a customer before creating an invoice. <a class="text-link" href="<?= e(url('contacts')) ?>">Open contacts</a></div><?php endif ?>
<form method="post" class="stack-form" id="invoice-form" action="<?= e(url('invoice')) ?>"><?= csrf_field() ?><div class="form-grid four"><label>Invoice number<input name="number" maxlength="80" value="<?= e(input('number','INV-'.date('Y').'-'.strtoupper(bin2hex(random_bytes(2))))) ?>" required></label><label>Customer<select name="contact_id" required><option value="">Choose customer</option><?php foreach($contacts as $c): ?><option value="<?= $c['id'] ?>"<?= selected(input('contact_id'),$c['id']) ?>><?= e($c['name']) ?></option><?php endforeach ?></select></label><label>Issue date<input type="date" name="issue_date" value="<?= e(input('issue_date',date('Y-m-d'))) ?>" required></label><label>Due date<input type="date" name="due_date" value="<?= e(input('due_date',date('Y-m-d',strtotime('+14 days')))) ?>" required></label></div>
<div class="section-heading"><h2>Line items</h2><button type="button" class="button small" data-add-item><?= icon('plus') ?>Add item</button></div><div id="invoice-items">
<?php $postedItems=is_post()&&is_array($_POST['item_description']??null)?$_POST['item_description']:['']; foreach($postedItems as $k=>$description): ?>
<div class="invoice-item"><label>Description<input name="item_description[]" value="<?= e(is_string($description)?$description:'') ?>" required maxlength="190"></label><label>Quantity<input name="quantity[]" type="number" min="0.01" max="10000" step="0.01" value="<?= e($_POST['quantity'][$k]??'1') ?>" required></label><label>Unit price (<?= e(workspace()['currency']) ?>)<input name="unit_price[]" type="number" min="0" step="0.01" value="<?= e($_POST['unit_price'][$k]??'') ?>" required></label><label>Tax %<input name="tax_rate[]" type="number" min="0" max="100" step="0.01" value="<?= e($_POST['tax_rate'][$k]??'21') ?>" required></label><button type="button" class="icon-button" data-remove-item title="Remove item" aria-label="Remove line item"><?= icon('x') ?></button></div>
<?php endforeach ?></div><div class="invoice-total-preview"><span>Estimated total</span><strong data-invoice-total data-currency="<?= e(workspace()['currency']) ?>"><?= money(0) ?></strong></div><label>Payment instructions / notes<textarea name="notes" rows="3" maxlength="5000"><?= e(input('notes')) ?></textarea></label><div class="form-actions"><button class="button primary"<?= !$contacts?' disabled':'' ?>><?= icon('check') ?>Save draft</button><a class="button" href="<?= e(url('invoices')) ?>">Cancel</a></div></form>
<?php else: ?>
<div class="invoice-sheet"><div class="invoice-party-grid"><div><span class="eyebrow">FROM</span><h2><?= e($invoice['seller_name']) ?></h2><p><?= nl2br(e($invoice['seller_address'])) ?></p><small><?= e($invoice['seller_registration']) ?></small></div><div><span class="eyebrow">BILL TO</span><h2><?= e($invoice['customer_name']) ?></h2><p><?= nl2br(e($invoice['customer_address'])) ?></p><small><?= e($invoice['customer_registration']) ?></small></div><div><span class="eyebrow">DATES</span><p>Issued <?= short_date($invoice['issue_date']) ?></p><p>Due <?= short_date($invoice['due_date']) ?></p></div></div>
<?php require ROOT.'/app/views/partials/invoice-items.php'; ?>
<?php if($invoice['notes']): ?><div class="invoice-notes"><h3>Notes</h3><p><?= nl2br(e($invoice['notes'])) ?></p></div><?php endif ?></div>
<form class="inline-form entry-actions" method="post" action="<?= e(url('invoice-action')) ?>"><?= csrf_field() ?><input type="hidden" name="id" value="<?= $invoice['id'] ?>"><?php if($invoice['status']==='draft'): ?><button class="button primary" name="action" value="sent"><?= icon('check') ?>Mark as sent</button><?php endif ?><?php if($invoice['status']==='sent'): ?><label>Payment date<input type="date" name="paid_on" value="<?= date('Y-m-d') ?>" required></label><button class="button primary" name="action" value="paid"><?= icon('check-check') ?>Record payment</button><?php endif ?><?php if(in_array($invoice['status'],['draft','sent'],true)): ?><button class="button danger" name="action" value="cancel" data-confirm="Cancel this invoice?">Cancel invoice</button><?php endif ?><?php if($invoice['entry_id']): ?><a class="button" href="<?= e(url('entry',['id'=>$invoice['entry_id']])) ?>">View income entry <?= icon('arrow-right') ?></a><?php endif ?></form>
<?php endif ?>
